apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-app-config
  namespace: video-processor
data:
  LOG_LEVEL: "INFO"
  PYTHONUNBUFFERED: "1"
  DATABASE_URL: "postgresql+asyncpg://postgres:postgres123@postgres-notification:5432/notification_db"
  REDIS_URL: "redis://redis:6379/3"
  AWS_ENDPOINT_URL: "http://localstack:4566"
  AWS_DEFAULT_REGION: "us-east-1"
  SQS_QUEUE_URL: "http://localstack:4566/000000000000/notification-queue"
  SQS_NOTIFICATION_QUEUE_URL: "http://localstack:4566/000000000000/notification-queue"
  SES_FROM_EMAIL: "noreply@videoprocessor.local"
  AUTH_SERVICE_URL: "http://auth-service:8000"
  JOB_SERVICE_URL: "http://job-api-service:8000"