apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: notification-worker-sqs-scaler
  namespace: video-processor
spec:
  scaleTargetRef:
    name: notification-worker
  pollingInterval: 15
  cooldownPeriod: 60
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: aws-sqs-queue
      authenticationRef:
        name: notification-worker-sqs-auth
      metadata:
        queueURLFromEnv: SQS_NOTIFICATION_QUEUE_URL
        queueLength: "5"
        awsRegion: "us-east-1"
        awsEndpoint: "http://localstack:4566"
        scaleOnInFlight: "true"